name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
      - uses: actions/checkout@master
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node-version }}
      - name: Composer Action
        uses: MilesChou/composer-action@master
        with:
          args: "install"
      - name: npm install, prod, and test
        run: |
          npm install
          npm run prod --if-present
          npm test --if-present
        env:
          CI: true
